### PR TITLE
Remove full screen option

### PR DESCRIPTION
**Pull request by KevinArtus**
[OO-FEATURE] Remove full screen for jarvis widget

### CODE REVIEW

**Comment by itkg-ngilain** [comment]
@KevinArtus: You can't alter that file as it is part of SmartAdmin, instead you should alter https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/master/BackofficeBundle/Resources/views/BackOffice/Underscore/Jarvis/header._tpl.twig which is the OpenOrchestra file used to render the fullscreen button

**Comment by itkg-ngilain** [comment]
Have you run the functional tests ?

**Comment by KevinArtus** [comment]
@itkg-ngilain I changed the right file.

**Comment by alavieille** [comment]
:+1:

**Pull request merged**
