### PR TITLE
use alias for document manager

### PR DESCRIPTION
**Pull request by itkg-rboessel**

### CODE REVIEW

**Comment by itkg-rboessel** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/982
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/29
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/396
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/78
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/7
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/40

**Comment by nicolasThal** [comment]
:+1:

**Comment by itkg-rboessel** [comment]
@nicolasThal renamming to object_manager done

**Comment by nicolasThal** [comment]
:+1: 

There should be a little part of the documentation which will mention it.

Could you create a ticket so we can talk about it in the ceremonie ?

**Pull request merged**
