### PR TITLE
Ergo pagination

### PR DESCRIPTION
**Pull request by itkg-alavieille**

### CODE REVIEW

**Comment by nicolasThal** [comment]
why did you put some hungarian notation ?

Did you found the plugin on bower?

**Comment by nicolasThal** [comment]
http://bower.io/docs/config/#shorthand-resolver

**Comment by itkg-alavieille** [comment]
because the dataTable plugin uses hungarian notation and I have not written all code.
what plugin ?

**Comment by itkg-alavieille** [comment]
@nicolasThal

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
