### PR TITLE
base security redirection on header or status code

### PR DESCRIPTION
**Pull request by nicolasThal**

### CODE REVIEW

**Comment by nicolasThal** [comment]
@juchi

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/75

**Comment by itkg-alavieille** [comment]
you can remove function isInText, it's never use

**Comment by juchi** [comment]
:+1:

**Comment by nicolasThal** [comment]
@itkg-alavieille pr updated

**Comment by itkg-alavieille** [comment]
:+1:

**Pull request merged**
