### PR TITLE
add new name to alternative file

### PR DESCRIPTION
**Pull request by aloupfor**
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1342
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/117
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/156

### CODE REVIEW

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by itkg-nanne** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
@itkg-nanne , @itkg-alavieille , @nicolasThal : PR from @aloupfor updated and needing a review

**Comment by SOLenG** [comment]
:+1:

**Comment by itkg-alavieille** [comment]
:+1:

**Pull request merged**
