### PR TITLE
replace span by div and update css

### PR DESCRIPTION
**Pull request by itkg-alavieille**

### CODE REVIEW

**Comment by juchi** [comment]
Wouldn't this be a good time to rename this class "display-block-icon-font" to something less CSSized ?

**Comment by itkg-alavieille** [comment]
what do you mean by CSSized

**Comment by juchi** [comment]
Prefixing the class with "display-block" infers the use of display:block (which is not good practice anyway), and a div is by default displayed as a block, so i guess it's no more needed (the prefix and the properties if they exist)

**Comment by itkg-alavieille** [comment]
i think the class does not refer to the css property but at blocks like (configurable content, content list, etc).  I will change it  just by block-icon-font. this will be more clear

**Comment by itkg-alavieille** [comment]
@juchi

**Comment by juchi** [comment]
:+1:

**Pull request merged**
