### PR TITLE
Add edit form custom template for content

### PR DESCRIPTION
**Pull request by itkg-ngilain**
Belongs to a pool of 3 PR :
open-orchestra-cms-bundle, open-orchestra-model-bundle, open-orchestra-model-interface

### CODE REVIEW

**Comment by nicolasThal** [comment]
You should also fix the tests :)

**Comment by itkg-ngilain** [comment]
@nicolasThal : updated

**Comment by nicolasThal** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
@nicolasThal : Add a forgotten part : the creation action

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
