### PR TITLE
fix functional test disabled voter

### PR DESCRIPTION
**Pull request by itkg-alavieille**

### CODE REVIEW

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
:+2:

**Comment by nicolasThal** [comment]
:-1:

**Comment by itkg-alavieille** [comment]
@nicolasThal why :-1:

**Comment by nicolasThal** [comment]
I disagree about this fix, the test was checking if the node could or could not be edited by the demo user.

This way, you should rather skip the test until the voter is fixed and the fixtures updated

**Comment by itkg-alavieille** [comment]
@nicolasThal

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
