### PR TITLE
fix display translated value

### PR DESCRIPTION
**Pull request by djamnazi**
[OO-BUGFIX] Fix the display of active tab of translated value form

https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/issues/114

### CODE REVIEW

**Comment by djamnazi** [comment]
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/issues/114

**Comment by ngilain** [comment]
:+1:

**Comment by alavieille** [comment]
:+1:

**Comment by KevinArtus** [comment]
Its not ok here :
capture du 2016-06-21 15-56-25

**Pull request merged**
