### PR TITLE
override backbone route method and remove addRoutePattern calls

### PR DESCRIPTION
**Pull request by aloupfor**

### CODE REVIEW

**Comment by itkg-canne** [comment]
:+1:

**Comment by aloupfor** [comment]
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/81

**Comment by itkg-alavieille** [comment]
:+1:  think to update doc

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by nicolasThal** [comment]
:+1: do not forgot to rebase master :)

**Comment by aloupfor** [comment]
https://github.com/open-orchestra/open-orchestra-docs/pull/128

**Pull request merged**
