### PR TITLE
Fix dashboard widgets

### PR DESCRIPTION
**Pull request by itkg-ngilain**
dev-master version of the fix

### CODE REVIEW

**Comment by itkg-alavieille** [comment]
i think that this is not the route that is inverted but the parameter of route : 
Replace : 
``
     * @Config\Route("/list/not-published-by-author", name="open_orchestra_api_node_list_author_not_published", defaults={"published": null})
     * @Config\Route("/list/by-author", name="open_orchestra_api_node_list_author", defaults={"published": false})
``
By : 

``

**Comment by itkg-ngilain** [comment]
You're right I close this PR as the v1.0 PR should fix it too (https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1088)

**Comment by itkg-ngilain** [comment]
@itkg-alavieille : update done

**Comment by itkg-alavieille** [comment]
:+1:

**Pull request merged**
