### PR TITLE
add translated title to block and panel

### PR DESCRIPTION
**Pull request by itkg-nanne**

### CODE REVIEW

**Comment by itkg-rboessel** [comment]
:+1:

**Comment by nicolasThal** [comment]
Did you update the documentation regarding the tabs?

**Comment by itkg-nanne** [comment]
@itkg-rboessel doesn't finish the documentation. He knows, he's got to change it. @nicolasThal

**Comment by nicolasThal** [comment]
As long as someone update it, it's cool :)

**Pull request merged**
