### PR TITLE
1.1 javascript tests

### PR DESCRIPTION
**Pull request by itkg-canne**
Here is a small sample of how we can integrate javascript unit testing with Travis.

On the first commit, I put a test that fails in order to validate that it leads to a failure into Travis (here is the related build : https://travis-ci.org/open-orchestra/open-orchestra-cms-bundle/builds/92885869 ).

On the second commit, I fixed the test, and it leads to a success into Travis (here is the related build : https://travis-ci.org/open-orchestra/open-orchestra-cms-bundle/builds/92886815 ).

### CODE REVIEW

**Comment by itkg-ngilain** [comment]
Sounds promising

**Comment by itkg-alavieille** [comment]
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1232
https://github.com/open-orchestra/open-orchestra/pull/811

**Comment by itkg-alavieille** [comment]
@itkg-ngilain @nicolasThal @SOLenG @Thiblef @itkg-nanne

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by nicolasThal** [comment]
:+1: 

I have a small question : is it possible to get the test task output as dot instead of strings ?

**Comment by itkg-alavieille** [comment]
@nicolasThal no There isn't option to change the output

**Pull request merged**
