### PR TITLE
add requirement php 5.6

### PR DESCRIPTION
**Pull request by alavieille**
[OO-MISC] Add requirement php: ~5.6.0

### CODE REVIEW

**Comment by itkg-canne** [comment]
:+1:

**Comment by clement-michelet** [comment]
What about a support of PHP 7.0 ? 
5.6 is in security support by the end of the year.

**Comment by alavieille** [comment]
we haven't check support of all vendor used by open orchestra for php 7.0 so for the time we can't indicate that open orchestra support php 7.0.

**Comment by itkg-ngilain** [comment]
:+1:

**Pull request merged**
