### PR TITLE
add version open orchestra in header

### PR DESCRIPTION
**Pull request by SOLenG**

### CODE REVIEW

**Comment by SOLenG** [comment]
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/52

**Comment by nicolasThal** [comment]
As the version is in a const, you could display const in the twig http://twig.sensiolabs.org/doc/tests/constant.html

**Comment by SOLenG** [comment]
@nicolasThal method fix

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
