### PR TITLE
change default value of the metaIndex and the metaFollow attributes in t...

### PR DESCRIPTION
**Pull request by itkg-alavieille**
...he site form

### CODE REVIEW

**Comment by itkg-nanne** [comment]
:+1:

**Comment by nicolasThal** [comment]
I would rather put this at default parameters when you create the site entity

**Comment by itkg-alavieille** [comment]
@nicolasThal

**Comment by nicolasThal** [comment]
It is much clearer !

But I don't see a test about the siteManager, can you write one?

**Comment by itkg-ngilain** [comment]
:+1:

**Comment by nicolasThal** [comment]
:+1: après un petit rebase de master

**Pull request merged**
