### PR TITLE
Remove ajax abort

### PR DESCRIPTION
**Pull request by itkg-nanne**

### CODE REVIEW

**Comment by nicolasThal** [comment]
I agree with the last commit.

If you want to merge it before the one on the site aliases you should be carefull

**Comment by itkg-ngilain** [comment]
Is there a rebase problem ? It seems you have two different operations there ?

**Comment by itkg-nanne** [comment]
done @nicolasThal , @itkg-ngilain

**Comment by itkg-ngilain** [comment]
:+1:

**Pull request merged**
