### PR TITLE
Change publication date form type from date to oo_date_picker

### PR DESCRIPTION
**Pull request by ngilain**
[OO-FEATURE] In node edition, publishing and unpublishing dates can be selected via a date picker

### CODE REVIEW

**Comment by ngilain** [comment]
@itkg-nanne : the picker doesn't appear in the form, but the date picker beahavior is correctly activated and no error is raised. Do you have an idea on the problem ?

**Comment by itkg-nanne** [comment]
As there is two oo_date_picker, it could be a conflict between them. Maybe try with only one. @ngilain

**Comment by ngilain** [comment]
@itkg-nanne : this is not the case as it doesn' t work more with only one. And it's correctly working on content type news with 2 date pickers. Plus there is absolutely no JS error.

**Comment by alavieille** [comment]
@ngilain the date picker work, it's just a problem with a z-indx, if you look DOM, you can see at the end the tag <div id='ui-datepicker-div'>...</div>

**Comment by ngilain** [comment]
@alavieille : update done

**Comment by alavieille** [comment]
:+1:

**Pull request merged**
