### PR TITLE
Remove container injection in LeftPanelManager

### PR DESCRIPTION
**Pull request by itkg-ngilain**

### CODE REVIEW

**Comment by nicolasThal** [comment]
I thought this was creating an injection loop...

**Comment by itkg-ngilain** [comment]
It's working, but I'll add some other refacto on top of this one : in the leftPanelInterface were dealing explicitly with the twigEngine, I'll replace those mentions with EngineInterface

**Comment by nicolasThal** [comment]
:+1:

**Comment by itkg-ngilain** [comment]
@nicolasThal : refacto done

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
