### PR TITLE
fix current language switcher

### PR DESCRIPTION
**Pull request by itkg-alavieille**

### CODE REVIEW

**Comment by nicolasThal** [comment]
On which case is the current locale not set?

**Comment by itkg-alavieille** [comment]
i don't understand your question , if the current locale not set i use defaultLocale of the context

**Comment by nicolasThal** [comment]
My question was : Where is the current locale set, and what is the use case where you can have no current locale set?

**Comment by itkg-alavieille** [comment]
the current locale is set in adminController (adminAction) if this action hasn't language in these parameters then the currentLocale isn't set.

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
